# Generated by Django 4.2.8 on 2023-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('sex', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine')], max_length=1, verbose_name='Sex')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
            ],
        ),
    ]
