# Generated by Django 4.2.8 on 2023-12-09 19:46

from django.db import migrations, models
import person.validators


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, validators=[person.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
